# -*- coding: utf-8 -*-
"""Web_Scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1va9wbxrSHatxrLl9NsjTxgx_hBu5sTuA
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def scrape_zaman_leaks(search_name):

    url = "https://leaks.zamanalwsl.net/1.5m.php"

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
        "Accept-Language": "ar,en-US;q=0.9,en;q=0.8"
    }

    params = {
        "firstname": search_name,
    }

    print(f"جاري إرسال الطلب للسيرفر للبحث عن: {search_name}...")

    try:
        # إرسال طلب GET مباشر لتخطي الـ CORS
        response = requests.get(url, headers=headers, params=params, timeout=20)
        response.raise_for_status() # للتأكد من نجاح الاتصال (Status Code 200)

        # تحليل استجابة السيرفر
        soup = BeautifulSoup(response.text, 'html.parser')

        # البحث عن الجدول الذي يحتوي على البيانات
        table = soup.find('table')

        # التحقق من وجود الجدول ومن أنه لا يحتوي على رسالة "No data available in table"
        if not table or "No data available" in table.text:
            print("لم يتم العثور على بيانات لهذا البحث، أو أن الجدول فارغ.")
            return

        # قراءة الجدول وتحويله مباشرة إلى DataFrame
        # نستخدم [0] لأن قراءة الـ HTML ترجع قائمة (List) من الجداول
        df = pd.read_html(str(table))[0]

        # إزالة أي صفوف فارغة ناتجة عن التنسيق
        df.dropna(how='all', inplace=True)

        print(f"تم سحب {len(df)} سجل بنجاح!")


        # نستخدم utf-8-sig لدعم اللغة العربية بشكل سليم في Excel
        filename = f"leaks_sample_{search_name}.csv"
        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f"تم حفظ البيانات في ملف: {filename}")

    except requests.exceptions.RequestException as e:
        print(f"حدث خطأ في الاتصال بالسيرفر: {e}")
    except ValueError:
         print("لم يتم العثور على جداول صالحة في صفحة الـ HTML.")

if __name__ == "__main__":
    # تجربة الكود بالبحث عن اسم شائع مثل "محمد" لاختبار الاستجابة
    scrape_zaman_leaks("محمد")